### ISSUE TITLE
Error run gstreamer-send

### ISSUE THREAD

**Issue by roberto497** [pion/example-webrtc-applications#157]
When trying to run the gstreamer-send example, the system outputs the SDP but closes shortly after with the following messages:

Exception 0xc0000005 0x0 0x0 0x7fffbf3663db
PC=0x7fffbf3663db
signal arrived during external code execution

runtime.cgocall(0x7ff69d7c8220, 0xc000399d20)
        C:/Program Files/Go/src/runtime/cgocall.go:157 +0x3e fp=0xc000399cf8 sp=0xc000399cc0 pc=0x7ff69d3a86fe
github.com/pion/example-webrtc-applications/v3/internal/gstreamer-src._Cfunc_free(0x2c86f09fc40)
        _cgo_gotypes.go:237 +0x49 fp=0xc000399d20 sp=0xc000399cf8 pc=0x7ff69d7c6549 
github.com/pion/example-webrtc-applications/v3/internal/gstreamer-src.goHandlePipelineBuffer.func2(0xc000153800?)
        E:/Projetos/example-webrtc-applications-master/internal/gstreamer-src/gst.go:132 +0x34 fp=0xc000399d58 sp=0xc000399d20 pc=0x7ff69d7c70d4
github.com/pion/example-webrtc-applications/v3/internal/gstreamer-src.goHandlePipelineBuffer(0xc000086000?, 0x0?, 0x1fca055, 0x9d409d01?)
        E:/Projetos/example-webrtc-applications-master/internal/gstreamer-src/gst.go:132 +0x14c fp=0xc000399e08 sp=0xc000399d58 pc=0x7ff69d7c6fac
_cgoexp_d211a7297ab8_goHandlePipelineBuffer(0x7ff69d944208?)
        _cgo_gotypes.go:304 +0x25 fp=0xc000399e30 sp=0xc000399e08 pc=0x7ff69d7c7225 
runtime.cgocallbackg1(0x7ff69d7c7200, 0x0?, 0x0)
        C:/Program Files/Go/src/runtime/cgocall.go:329 +0x2c2 fp=0xc000399f00 sp=0xc000399e30 pc=0x7ff69d3a8c82
runtime.cgocallbackg(0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/cgocall.go:245 +0x109 fp=0xc000399f90 sp=0xc000399f00 pc=0x7ff69d3a88e9
runtime.cgocallbackg(0x7ff69d7c7200, 0xcabf5fe3b0, 0x0)
        <autogenerated>:1 +0x2e fp=0xc000399fb8 sp=0xc000399f90 pc=0x7ff69d41070e   
runtime.cgocallback(0x0, 0x0, 0x0)
        C:/Program Files/Go/src/runtime/asm_amd64.s:1035 +0xec fp=0xc000399fe0 sp=0xc000399fb8 pc=0x7ff69d40baac
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000399fe8 sp=0xc000399fe0 pc=0x7ff69d40bd21

goroutine 1 [select (no cases)]:
runtime.gopark(0x0?, 0x0?, 0x1?, 0x0?, 0x2c86e72b180?)
        C:/Program Files/Go/src/runtime/proc.go:398 +0xce fp=0xc000643da8 sp=0xc000643d88 pc=0x7ff69d3de98e
runtime.block()
        C:/Program Files/Go/src/runtime/select.go:103 +0x26 fp=0xc000643dd8 sp=0xc000643da8 pc=0x7ff69d3ecde6
main.main()
        E:/Projetos/example-webrtc-applications-master/gstreamer-send/main.go:112 +0x694 fp=0xc000643f40 sp=0xc000643dd8 pc=0x7ff69d7c7f94
runtime.main()
        C:/Program Files/Go/src/runtime/proc.go:267 +0x2b2 fp=0xc000643fe0 sp=0xc000643f40 pc=0x7ff69d3de572
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000643fe8 sp=0xc000643fe0 pc=0x7ff69d40bd21

goroutine 17 [syscall, locked to thread]:
runtime.cgocall(0x7ff69d7c8220, 0xc00005fd20)
        C:/Program Files/Go/src/runtime/cgocall.go:157 +0x3e fp=0xc00005fcf8 sp=0xc00005fcc0 pc=0x7ff69d3a86fe
github.com/pion/example-webrtc-applications/v3/internal/gstreamer-src._Cfunc_free(0x2c86ee28820)
        _cgo_gotypes.go:237 +0x49 fp=0xc00005fd20 sp=0xc00005fcf8 pc=0x7ff69d7c6549 
github.com/pion/example-webrtc-applications/v3/internal/gstreamer-src.goHandlePipelineBuffer.func2(0xc000602500?)
        E:/Projetos/example-webrtc-applications-master/internal/gstreamer-src/gst.go:132 +0x34 fp=0xc00005fd58 sp=0xc00005fd20 pc=0x7ff69d7c70d4
github.com/pion/example-webrtc-applications/v3/internal/gstreamer-src.goHandlePipelineBuffer(0xc000086000?, 0x0?, 0xcdfe60, 0x9d409d01?)
        E:/Projetos/example-webrtc-applications-master/internal/gstreamer-src/gst.go:132 +0x14c fp=0xc00005fe08 sp=0xc00005fd58 pc=0x7ff69d7c6fac
_cgoexp_d211a7297ab8_goHandlePipelineBuffer(0x7ff69d944208?)
        _cgo_gotypes.go:304 +0x25 fp=0xc00005fe30 sp=0xc00005fe08 pc=0x7ff69d7c7225
runtime.cgocallbackg1(0x7ff69d7c7200, 0x0?, 0x0)
        C:/Program Files/Go/src/runtime/cgocall.go:329 +0x2c2 fp=0xc00005ff00 sp=0xc00005fe30 pc=0x7ff69d3a8c82
runtime.cgocallbackg(0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/cgocall.go:245 +0x109 fp=0xc00005ff90 sp=0xc00005ff00 pc=0x7ff69d3a88e9
runtime.cgocallbackg(0x7ff69d7c7200, 0xcabf3fea70, 0x0)
        <autogenerated>:1 +0x2e fp=0xc00005ffb8 sp=0xc00005ff90 pc=0x7ff69d41070e   
runtime.cgocallback(0x0, 0x0, 0x0)
        C:/Program Files/Go/src/runtime/asm_amd64.s:1035 +0xec fp=0xc00005ffe0 sp=0xc00005ffb8 pc=0x7ff69d40baac
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005ffe8 sp=0xc00005ffe0 pc=0x7ff69d40bd21

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:398 +0xce fp=0xc000059fa8 sp=0xc000059f88 pc=0x7ff69d3de98e
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:404
runtime.forcegchelper()
        C:/Program Files/Go/src/runtime/proc.go:322 +0xb8 fp=0xc000059fe0 sp=0xc000059fa8 pc=0x7ff69d3de818
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000059fe8 sp=0xc000059fe0 pc=0x7ff69d40bd21
created by runtime.init.6 in goroutine 1
        C:/Program Files/Go/src/runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:398 +0xce fp=0xc00005bf78 sp=0xc00005bf58 pc=0x7ff69d3de98e
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
        C:/Program Files/Go/src/runtime/mgcsweep.go:321 +0xdf fp=0xc00005bfc8 sp=0xc00005bf78 pc=0x7ff69d3c919f
runtime.gcenable.func1()
        C:/Program Files/Go/src/runtime/mgc.go:200 +0x25 fp=0xc00005bfe0 sp=0xc00005bfc8 pc=0x7ff69d3be2e5
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005bfe8 sp=0xc00005bfe0 pc=0x7ff69d40bd21
created by runtime.gcenable in goroutine 1
        C:/Program Files/Go/src/runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000064000?, 0x7ff69d9b7d88?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:398 +0xce fp=0xc00006bf70 sp=0xc00006bf50 pc=0x7ff69d3de98e
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x7ff69dc938e0)
        C:/Program Files/Go/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc00006bfa0 sp=0xc00006bf70 pc=0x7ff69d3c6a29
runtime.bgscavenge(0x0?)
        C:/Program Files/Go/src/runtime/mgcscavenge.go:658 +0x59 fp=0xc00006bfc8 sp=0xc00006bfa0 pc=0x7ff69d3c6fd9
runtime.gcenable.func2()
        C:/Program Files/Go/src/runtime/mgc.go:201 +0x25 fp=0xc00006bfe0 sp=0xc00006bfc8 pc=0x7ff69d3be285
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00006bfe8 sp=0xc00006bfe0 pc=0x7ff69d40bd21
created by runtime.gcenable in goroutine 1
        C:/Program Files/Go/src/runtime/mgc.go:201 +0xa5

goroutine 18 [finalizer wait]:
runtime.gopark(0x198?, 0x7ff69d901d80?, 0x1?, 0xf8?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:398 +0xce fp=0xc00005de20 sp=0xc00005de00 pc=0x7ff69d3de98e
runtime.runfinq()
        C:/Program Files/Go/src/runtime/mfinal.go:193 +0x107 fp=0xc00005dfe0 sp=0xc00005de20 pc=0x7ff69d3bd347
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005dfe8 sp=0xc00005dfe0 pc=0x7ff69d40bd21
created by runtime.createfing in goroutine 1
        C:/Program Files/Go/src/runtime/mfinal.go:163 +0x3d

goroutine 19 [syscall]:
runtime.cgocall(0x7ff69d7c8270, 0xc000067fd0)
        C:/Program Files/Go/src/runtime/cgocall.go:157 +0x3e fp=0xc000067fa8 sp=0xc000067f70 pc=0x7ff69d3a86fe
github.com/pion/example-webrtc-applications/v3/internal/gstreamer-src._Cfunc_gstreamer_send_start_mainloop()
        _cgo_gotypes.go:263 +0x49 fp=0xc000067fd0 sp=0xc000067fa8 pc=0x7ff69d7c6689 
github.com/pion/example-webrtc-applications/v3/internal/gstreamer-src.init.0.func1()
        E:/Projetos/example-webrtc-applications-master/internal/gstreamer-src/gst.go:27 +0x18 fp=0xc000067fe0 sp=0xc000067fd0 pc=0x7ff69d7c71b8
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000067fe8 sp=0xc000067fe0 pc=0x7ff69d40bd21
created by github.com/pion/example-webrtc-applications/v3/internal/gstreamer-src.init.0 in goroutine 1
        E:/Projetos/example-webrtc-applications-master/internal/gstreamer-src/gst.go:27 +0x1a

goroutine 20 [select]:
runtime.gopark(0xc000069f78?, 0x2?, 0xb6?, 0x8f?, 0xc000069f4c?)
        C:/Program Files/Go/src/runtime/proc.go:398 +0xce fp=0xc000069df0 sp=0xc000069dd0 pc=0x7ff69d3de98e
runtime.selectgo(0xc000069f78, 0xc000069f48, 0x7ff69d9bbdc0?, 0x0, 0x0?, 0x1)       
        C:/Program Files/Go/src/runtime/select.go:327 +0x725 fp=0xc000069f10 sp=0xc000069df0 pc=0x7ff69d3ed525
github.com/pion/interceptor/pkg/nack.(*GeneratorInterceptor).loop(0xc0000de1e0, {0x7ff69d9bbdc0, 0xc00008fbb0})
        C:/Users/rober/go/pkg/mod/github.com/pion/interceptor@v0.1.25/pkg/nack/generator_interceptor.go:147 +0x125 fp=0xc000069fb8 sp=0xc000069f10 pc=0x7ff69d7706e5    
github.com/pion/interceptor/pkg/nack.(*GeneratorInterceptor).BindRTCPWriter.func2() 
        C:/Users/rober/go/pkg/mod/github.com/pion/interceptor@v0.1.25/pkg/nack/generator_interceptor.go:81 +0x28 fp=0xc000069fe0 sp=0xc000069fb8 pc=0x7ff69d76ff88      
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=

**Comment by Sean-Der** [comment]
Sorry I didn't respond sooner @roberto497!

This bug is gone because we switched to https://github.com/go-gst/go-gst before we had all the C/GStreamer code in tree and you hit a double free looks like :(
